project_id = "nbvvdaprcecaqvvkqcto"

[functions.zapier-webhook]
verify_jwt = false

[functions.process-zapier-webhooks]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = false

[functions.link-invitation]
verify_jwt = true

[functions.validate-password]
verify_jwt = false

[functions.cleanup-logs]
verify_jwt = true

[functions.mfa-verify]
verify_jwt = false

[functions.mfa-generate-secret]
verify_jwt = true

[functions.security-alerts]
verify_jwt = true

[functions.resend-verification-email]
verify_jwt = false

[functions.request-sell-collaboration]
verify_jwt = true