project_id = "nbvvdaprcecaqvvkqcto"

[functions.admin-list-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.link-invitation]
verify_jwt = true

[functions.validate-password]
verify_jwt = false

[functions.cleanup-logs]
verify_jwt = true

[functions.mfa-verify]
verify_jwt = false