# Netlify configuration for Capittal app
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  command = "npm run build"

# Cache headers for optimal performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files should not be cached to ensure latest version
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://nbvvdaprcecaqvvkqcto.supabase.co https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://nbvvdaprcecaqvvkqcto.supabase.co https://api.ipify.org wss://nbvvdaprcecaqvvkqcto.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
